production:
  adapter: mysql
  database: tenniscity_production
  host: localhost
  username: root
  password: 
  encoding: utf8
 
development:
  adapter: mysql
  database: tenniscity_development
  host: localhost
  username: root
  password:
  encoding: utf8

test: &TEST
  adapter: mysql
  database: tenniscity_test
  host: localhost
  username: root
  password:
  encoding: utf8

cucumber:
  <<: *TEST